workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(master|develop)$/ && $CI_PIPELINE_SOURCE == "merge_request_event"

image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - publish
  - deploy_on_test